import { inventory, offers, products } from "../src/data.js";

const seedProducts = products.map((product, index) => ({
  id: `PROD-${String(index + 1).padStart(3, "0")}`,
  inventoryId: inventory[index]?.id ?? null,
  ...product,
}));

const seedUsers = [
  {
    id: "user-seller-demo",
    email: "seller@jaanu.com",
    password: "seller123",
    role: "SELLER",
    businessName: "Jaanu Luxe House",
    wishlistProductIds: [],
    bagItems: [],
    createdAt: "2026-01-05T09:00:00.000Z",
    lastActiveAt: "2026-04-03T08:00:00.000Z",
    isGuest: false,
  },
  {
    id: "user-customer-demo",
    email: "priya.sharma@email.com",
    password: "customer123",
    role: "CUSTOMER",
    businessName: "",
    wishlistProductIds: ["PROD-001", "PROD-005"],
    bagItems: [
      {
        id: "bag-001",
        productId: "PROD-002",
        addedAt: "2026-04-03T07:45:00.000Z",
      },
    ],
    createdAt: "2026-01-15T10:00:00.000Z",
    lastActiveAt: "2026-04-03T08:00:00.000Z",
    isGuest: false,
  },
];

const seedOrders = [
  {
    id: "#OD1024",
    product: "Rose embroidered saree",
    customerId: "user-customer-demo",
    customer: "Priya Sharma",
    customerEmail: "priya.sharma@email.com",
    customerPhone: "+91 98765 43210",
    customerLocation: "Delhi, India",
    status: "Pending",
    amount: "Rs 4,500",
    date: "2026-04-03",
    payment: "UPI",
    items: 1,
    totalSpent: 4500,
    joinDate: "2026-01-15",
    lastOrder: "2026-04-03",
  },
  {
    id: "#OD1025",
    product: "Silk blend kurta",
    customerId: "user-anjali",
    customer: "Anjali Kapoor",
    customerEmail: "anjali.kapoor@email.com",
    customerPhone: "+91 87654 32109",
    customerLocation: "Mumbai, India",
    status: "Shipped",
    amount: "Rs 2,800",
    date: "2026-04-02",
    payment: "COD",
    items: 1,
    totalSpent: 2800,
    joinDate: "2026-02-20",
    lastOrder: "2026-04-02",
  },
  {
    id: "#OD1026",
    product: "Bridal lehenga choli",
    customerId: "user-meera",
    customer: "Meera Patel",
    customerEmail: "meera.patel@email.com",
    customerPhone: "+91 76543 21098",
    customerLocation: "Ahmedabad, India",
    status: "Delivered",
    amount: "Rs 12,500",
    date: "2026-04-01",
    payment: "Card",
    items: 1,
    totalSpent: 12500,
    joinDate: "2025-12-10",
    lastOrder: "2026-04-01",
  },
  {
    id: "#OD1027",
    product: "Handwoven dupatta",
    customerId: "user-kavita",
    customer: "Kavita Singh",
    customerEmail: "kavita.singh@email.com",
    customerPhone: "+91 65432 10987",
    customerLocation: "Jaipur, India",
    status: "Delivered",
    amount: "Rs 1,200",
    date: "2026-03-30",
    payment: "UPI",
    items: 1,
    totalSpent: 1200,
    joinDate: "2026-03-01",
    lastOrder: "2026-03-30",
  },
  {
    id: "#OD1028",
    product: "Designer dress",
    customerId: "user-riya",
    customer: "Riya Gupta",
    customerEmail: "riya.gupta@email.com",
    customerPhone: "+91 54321 09876",
    customerLocation: "Pune, India",
    status: "Cancelled",
    amount: "Rs 3,200",
    date: "2026-03-28",
    payment: "UPI",
    items: 1,
    totalSpent: 0,
    joinDate: "2026-03-15",
    lastOrder: "2026-03-28",
  },
  {
    id: "#OD1029",
    product: "Cotton t-shirt",
    customerId: "user-sneha",
    customer: "Sneha Reddy",
    customerEmail: "sneha.reddy@email.com",
    customerPhone: "+91 43210 98765",
    customerLocation: "Hyderabad, India",
    status: "Delivered",
    amount: "Rs 800",
    date: "2026-03-25",
    payment: "COD",
    items: 1,
    totalSpent: 800,
    joinDate: "2026-03-10",
    lastOrder: "2026-03-25",
  },
  {
    id: "#OD1030",
    product: "Gold plated jewelry set",
    customerId: "user-pooja",
    customer: "Pooja Jain",
    customerEmail: "pooja.jain@email.com",
    customerPhone: "+91 32109 87654",
    customerLocation: "Indore, India",
    status: "Shipped",
    amount: "Rs 2,500",
    date: "2026-03-22",
    payment: "Card",
    items: 1,
    totalSpent: 2500,
    joinDate: "2025-11-05",
    lastOrder: "2026-03-22",
  },
  {
    id: "#OD1031",
    product: "Designer handbag",
    customerId: "user-aisha",
    customer: "Aisha Khan",
    customerEmail: "aisha.khan@email.com",
    customerPhone: "+91 21098 76543",
    customerLocation: "Kolkata, India",
    status: "Delivered",
    amount: "Rs 3,500",
    date: "2026-03-20",
    payment: "UPI",
    items: 1,
    totalSpent: 3500,
    joinDate: "2026-01-08",
    lastOrder: "2026-03-20",
  },
  {
    id: "#OD1032",
    product: "Silk blend kurta",
    customerId: "user-customer-demo",
    customer: "Priya Sharma",
    customerEmail: "priya.sharma@email.com",
    customerPhone: "+91 98765 43210",
    customerLocation: "Delhi, India",
    status: "Delivered",
    amount: "Rs 2,800",
    date: "2026-03-18",
    payment: "COD",
    items: 1,
    totalSpent: 7300,
    joinDate: "2026-01-15",
    lastOrder: "2026-04-03",
  },
  {
    id: "#OD1033",
    product: "Handwoven dupatta",
    customerId: "user-meera",
    customer: "Meera Patel",
    customerEmail: "meera.patel@email.com",
    customerPhone: "+91 76543 21098",
    customerLocation: "Ahmedabad, India",
    status: "Processing",
    amount: "Rs 1,200",
    date: "2026-03-15",
    payment: "UPI",
    items: 1,
    totalSpent: 13700,
    joinDate: "2025-12-10",
    lastOrder: "2026-04-01",
  },
];

const seedActivityFeed = [
  {
    id: "activity-001",
    type: "system.ready",
    message: "Realtime marketplace backend started successfully.",
    createdAt: "2026-04-03T08:00:00.000Z",
  },
  {
    id: "activity-002",
    type: "order.pending",
    message: "Priya Sharma placed order #OD1024.",
    createdAt: "2026-04-03T08:05:00.000Z",
  },
  {
    id: "activity-003",
    type: "inventory.low_stock",
    message: "Cotton T-Shirt stock dropped to 2 available units.",
    createdAt: "2026-04-03T08:10:00.000Z",
  },
];

const seedReviews = [
  {
    id: "review-001",
    customerName: "Priya Sharma",
    customerAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=150&q=80",
    product: "Rose Embroidered Saree",
    rating: 5,
    date: "2026-04-01",
    review: "Absolutely stunning saree! The embroidery work is exquisite and the quality is top-notch.",
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=300&q=80"],
    helpful: 12,
    verified: true,
    status: "published",
    reply: "",
  },
  {
    id: "review-002",
    customerName: "Rahul Verma",
    customerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    product: "Premium Casual Sneakers",
    rating: 4,
    date: "2026-03-28",
    review: "Great comfort and stylish design. The only issue is that they run a bit large.",
    images: [],
    helpful: 8,
    verified: true,
    status: "published",
    reply: "",
  },
  {
    id: "review-003",
    customerName: "Anjali Patel",
    customerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80",
    product: "Tailored Co-ord Set",
    rating: 5,
    date: "2026-03-26",
    review: "Love this co-ord set. Perfect fit and the fabric is so comfortable.",
    images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=300&q=80"],
    helpful: 15,
    verified: true,
    status: "published",
    reply: "",
  },
  {
    id: "review-004",
    customerName: "Vikram Singh",
    customerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
    product: "Designer Lehenga",
    rating: 3,
    date: "2026-03-22",
    review: "The lehenga is beautiful but took longer than expected for delivery.",
    images: [],
    helpful: 3,
    verified: true,
    status: "published",
    reply: "",
  },
];

export function createSeedState() {
  return {
    products: seedProducts,
    offers,
    inventory,
    orders: seedOrders,
    users: seedUsers,
    reviews: seedReviews,
    settings: {
      storeName: "Jaanu Fashion Store",
      storeDescription: "Premium ethnic and western wear for modern women",
      contactEmail: "support@jaanufashion.com",
      contactPhone: "+91 98765 43210",
      address: "123 Fashion Street, Mumbai, Maharashtra 400001",
      businessHours: "Mon-Sat: 10 AM - 8 PM, Sun: 11 AM - 6 PM",
      returnPolicy: "30 days return policy for all items",
      shippingPolicy: "Free shipping on orders above Rs 999",
      paymentMethods: ["Credit Card", "Debit Card", "UPI", "Net Banking", "Cash on Delivery"],
      socialLinks: {
        instagram: "https://instagram.com/jaanufashion",
        facebook: "https://facebook.com/jaanufashion",
        twitter: "https://twitter.com/jaanufashion",
      },
      notifications: {
        emailOrders: true,
        emailReviews: true,
        emailMarketing: false,
        smsOrders: true,
        pushNotifications: true,
      },
    },
    activityFeed: seedActivityFeed,
    counters: {
      order: 1034,
      guest: 1,
      bagItem: 1,
      activity: 3,
      product: seedProducts.length,
      offer: offers.length,
      inventory: inventory.length,
    },
  };
}
